# Generated by Django 3.0.4 on 2020-04-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='/gallery/default.jpg', upload_to='gallery'),
        ),
    ]
