# Generated by Django 3.0.4 on 2020-03-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200331_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='blog/static/media/django-gettingstarted.jpg', upload_to='blog/static/media'),
        ),
    ]
